CREATE SEQUENCE rentcar20230623_no START WITH 1;

CREATE TABLE rentcar20230623 (
    no NUMBER DEFAULT rentcar20230623_no.NEXTVAL PRIMARY KEY,
    name VARCHAR2(20) NOT NULL,
    category NUMBER,
    price NUMBER DEFAULT ON NULL -1 NOT NULL,
    user_people NUMBER DEFAULT ON NULL -1 NOT NULL,
    company VARCHAR2(50) NOT NULL,
    img VARCHAR2(50),
    info VARCHAR2(500) NOT NULL
);

CREATE SEQUENCE carreserve20230623_no START WITH 1;

CREATE TABLE carreserve20230623 (
    reserve_seq NUMBER DEFAULT carreserve20230623_no.NEXTVAL PRIMARY KEY;
    no NUMBER REFERENCES rentcar20230623(no),
    id VARCHAR2(30),
    qty NUMBER NOT NULL,
    dday NUMBER NOT NULL,
    rday TIMESTAMP NOT NULL,
    usein NUMBER NOT NULL,
    usewifi NUMBER NOT NULL,
    usenavi NUMBER NOT NULL,
    useseat NUMBER NOT NULL
);

COMMIT;
